export const ui = {
  pageSection: 'space-y-12',
  pageKicker: 'text-xs font-medium uppercase tracking-[0.24em] text-white/45',
  pageTitle: 'mt-2 text-3xl font-semibold tracking-tight text-white',
  pageSubtitle: 'mt-3 text-sm leading-6 text-white/60',
  section: 'space-y-3',
  sectionCard: 'space-y-3 p-6 border border-white/90 max-w-2xl rounded',
  bodyText: 'text-sm leading-6 text-white/60',
  helperText: 'text-xs leading-6 text-white/45',
  fieldLabel: 'text-xs font-semibold uppercase tracking-[0.2em] text-white/45',
  input: 'h-9 rounded-md border border-white/10 bg-[#262633] px-3 text-sm text-white/90 outline-none focus:border-white/20 disabled:opacity-60',
  select: 'h-9 w-full rounded-md border border-white/10 bg-[#262633] px-3 text-sm text-white/90 outline-none focus:border-white/20 disabled:opacity-60',
  textarea: 'min-h-22.5 resize-y bg-[#262633] border-0',
  listStack: 'space-y-4',
  listItem: 'flex flex-col gap-2 py-2',
  listItemHeader: 'flex items-start justify-between gap-4',
  listItemTitle: 'text-sm font-semibold text-white',
  listItemDescription: 'text-sm text-white/60',
  metaText: 'text-xs text-white/45',
  formCard: 'space-y-4 pt-4',
  formGrid: 'grid gap-2',
}
